export const INCREMENT = "[HOME SECTION] INCREMENT COUNTER";
export const INCREMENT_ASYNC = "[HOME SECTION] INCREMENT COUNTER ASYNC";
export const DECREMENT = "[HOME SECTION] DECREMENT COUNTER";
export const DECREMENT_ASYNC = "[HOME SECTION] DECREMENT COUNTER ASYNC";
